Seemingly somewhere in the emrging of the csvs in the indicator script, for some coutnries some months were dropped, therefore from the single dfs, they will be merged new into set final df

In [1]:
import pandas as pd

In [29]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)
pd.set_option('display.width', 1000)

In [2]:
def pivot_table(df, index, columns, values):
    pivot = df.pivot_table(
        index=index,
        columns=columns,
        values=values,
        aggfunc='sum'
    ).reset_index().fillna(0)
    return pivot

def build_pivot_set(df, index_col, group_col, value_cols, rename_fn):
    tables = [
        rename_fn(pivot_table(df, index_col, group_col, col), col)
        for col in value_cols
    ]
    result = tables[0]
    for t in tables[1:]:
        result = result.merge(t, on=index_col)
    return result

In [3]:
def rename_contrib_type(df, contrib_type):
    df = df.rename(columns={
        'CREATION':f'{contrib_type}_creation',
         'DELETION':f'{contrib_type}_deletion',
         'GEOMETRY':f'{contrib_type}_geometry',
        'TAG':f'{contrib_type}_tag',
        'TAG_GEOMETRY':f'{contrib_type}_tag_geometry'
    })
    return df

def rename_feature_type(df, feature_type):
    df = df.rename(columns={
        'building':f'{feature_type}_building',
         'highway':f'{feature_type}_highway',
         'other':f'{feature_type}_other'
    })
    return df

In [11]:
months = pd.read_csv("months.csv")

In [5]:
contrib_cols = ['contributors', 'contributors_ai', 'changesets', 'changesets_ai', 'edits', 'edits_ai']
feature_specs = ['contributors', 'contributors_ai', 'share_contributors', 'edits','edits_ai', 'share_edits', 'changesets', 'changesets_ai', 'share_changesets']

In [50]:
def update_indicator_df(country):
    monthly_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_monthly_stats.csv")
    contrib_type_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_contrib_type.csv")
    feature_type_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_feature_type.csv")
    xp_monthly = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_updated_monthly_experience_ohsome.csv")
    affiliation_all_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_affiliation_all.csv")
    affiliation_hot_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_affiliation_hot.csv")
    affiliation_ai_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_affiliation_hot.csv")
    retention_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_retention.csv")
    survival_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_survival.csv")
    monthly_interaction_network_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_monthly_interaction_network.csv")
    comments_notes_df = pd.read_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_comments_notes_total.csv")

    contrib_type_df_long = build_pivot_set(contrib_type_df, 'months', 'contrib_type', contrib_cols, rename_contrib_type)
    feature_type_df_long = build_pivot_set(feature_type_df, 'months', 'tag_type', feature_specs, rename_feature_type)

    #creating one big csv with all monthly indicators
    #using the complete months as first input, so all needed months are there, useing left join for all others so all months are guaranteed
    big_monthly_df = months.merge(monthly_df[["months", "editsPerc", "changesetsPerc", "contributorsPerc", "global_new_contrib", "local_new_contrib", "new_contrib_ai", "new_contrib_non_ai"]], on ="months", how="left")

    big_monthly_df = big_monthly_df.merge(affiliation_all_df, on ="months", how="left")
    big_monthly_df = big_monthly_df.merge(xp_monthly, on = "months", how="left")
    big_monthly_df = big_monthly_df.merge(comments_notes_df, on = "months", how="left")
    big_monthly_df = big_monthly_df.merge(contrib_type_df_long, on = "months", how="left")
    big_monthly_df = big_monthly_df.merge(feature_type_df_long, on = "months", how="left")
    big_monthly_df = big_monthly_df.merge(retention_df, on = "months", how="left")
    big_monthly_df = big_monthly_df.merge(monthly_interaction_network_df[["months", "mean_degree"]], on = "months", how="left")
    
    #calculating massing ratios / shares
    big_monthly_df["changesets_corporate_share"] =big_monthly_df["changesets_corporate"] / big_monthly_df["changesets"]
    big_monthly_df["contributors_corporate_share"] =big_monthly_df["contributors_corporate"] / big_monthly_df["contributors"]
    
    big_monthly_df["changesets_humanitarian_share"] =big_monthly_df["changesets_humanitarian"] / big_monthly_df["changesets"]
    big_monthly_df["contributors_humanitarian_share"] =big_monthly_df["contributors_humanitarian"] / big_monthly_df["contributors"]
    
    big_monthly_df["changesets_ai_share"]= big_monthly_df["changesetsPerc"]/100
    big_monthly_df["contributors_ai_share"]= big_monthly_df["contributorsPerc"]/100
    big_monthly_df["new_contributors_ai_share"]= big_monthly_df["new_contrib_ai"] / (big_monthly_df["global_new_contrib"] + big_monthly_df["local_new_contrib"])
    
    big_monthly_df["contributors_prolific_share_ai_total"]= big_monthly_df["contributors_prolific_ai"]/big_monthly_df["contributors"]
    big_monthly_df["contributors_casual_share_ai_total"]= big_monthly_df["contributors_casual_ai"]/big_monthly_df["contributors"]
    big_monthly_df["contributors_prolific_share_total"]= big_monthly_df["contributors_prolific_total"]/big_monthly_df["contributors"]
    big_monthly_df["contributors_casual_share_total"]= big_monthly_df["contributors_casual_total"]/big_monthly_df["contributors"]
    
    big_monthly_df["contributors_inactive_share_total"]= big_monthly_df["contributors_inactive_total"]/big_monthly_df["contributors"]
    big_monthly_df["contributors_inactive_share_ai_total"]= big_monthly_df["contributors_inactive_ai"]/big_monthly_df["contributors"]
    
    big_monthly_df["global_new_contrib_share"]= big_monthly_df["global_new_contrib"]/big_monthly_df["contributors"]
    big_monthly_df["building_changesets_share"] = big_monthly_df["changesets_building"] / big_monthly_df["changesets"]
    big_monthly_df["highway_changesets_share"] = big_monthly_df["changesets_highway"] / big_monthly_df["changesets"]
    big_monthly_df["building_changesets_ai_share"] = big_monthly_df["changesets_ai_building"] / big_monthly_df["changesets"]
    big_monthly_df["highway_changesets_ai_share"] = big_monthly_df["changesets_ai_highway"] / big_monthly_df["changesets"]
    
    #added from Spearman 
    big_monthly_df["total_new_contrib"] = big_monthly_df["global_new_contrib"] + big_monthly_df["local_new_contrib"]
    big_monthly_df["edits_corporate_share"] =big_monthly_df["edits_corporate"] / big_monthly_df["edits"]
    big_monthly_df["edits_humanitarian_share"] =big_monthly_df["edits_humanitarian"] / big_monthly_df["edits"]
    big_monthly_df["edits_ai_share"]= big_monthly_df["editsPerc"]/100
    big_monthly_df["edits_building_share"]= big_monthly_df["share_edits_building"]/100
    big_monthly_df["edits_other_share"]= big_monthly_df["share_edits_other"]/100
    big_monthly_df["edits_highway_share"]= big_monthly_df["share_edits_highway"]/100
    
    #new columns --> need new measure for contributors_AI since there are lsight differences between duckdb queries and ohsome_now query
    big_monthly_df["contributors_ai_ohsome"] = big_monthly_df["contributors_inactive_ai"] + big_monthly_df["contributors_prolific_ai"] +big_monthly_df["contributors_casual_ai"]
    big_monthly_df["contributors_inactive_share_ai"]= big_monthly_df["contributors_inactive_ai"]/big_monthly_df["contributors_ai_ohsome"]
    big_monthly_df["contributors_prolific_share_ai"]= big_monthly_df["contributors_prolific_ai"]/big_monthly_df["contributors_ai_ohsome"]
    big_monthly_df["contributors_casual_share_ai"]= big_monthly_df["contributors_casual_ai"]/big_monthly_df["contributors_ai_ohsome"]
    
    big_monthly_df['new_contrib_ai_share'] = big_monthly_df['new_contrib_ai']/big_monthly_df['total_new_contrib']

    big_monthly_df = big_monthly_df.fillna(0)
    indicators_df = big_monthly_df[['months', 'contributors', 'changesets', 'edits','mean_degree', 'active_users', 'total_new_contrib' , 
    'changeset_comments_ai', 'ratio_active_users_ai',
    'changesets_corporate_share', 'contributors_corporate_share', 'changesets_humanitarian_share', 'contributors_humanitarian_share', 
    'edits_corporate_share', 'edits_humanitarian_share', 'edits_ai_share', 
    'changesets_ai_share', 'contributors_ai_share', 'contributors_prolific_share_ai', 'contributors_casual_share_ai','contributors_inactive_share_ai',
    'building_changesets_share', 'highway_changesets_share', 'building_changesets_ai_share', 'highway_changesets_ai_share',
    'new_contributors_ai_share', 'notes_length',
    'contributors_prolific_share_ai_total', 'contributors_casual_share_ai_total', 'contributors_inactive_share_ai_total','retention_rate_ai', 'new_contrib_ai_share'
    ]].copy()

    indicators_df.to_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_prepped_indicators_stat_update.csv", index = False)
    big_monthly_df.to_csv(rf"..\..\data\ouput\country_analysis\v5_indicators\{country}\{country}_all_monthly_metrics_update.csv", index = False)

In [51]:
update_indicator_df("ALB")

In [56]:
countries = ["AFG", "ALB", "BGD", "BOL", "BTN", "BRN", "COL", "CYP", "ECU", "ETH", "B35", "GRC", "HUN", "IND", "KEN", "KHM", "KOR",
             "LAO", "MAR", "MKD", "MNE", "NGA", "NZ1", "PNG", "SAU", "SLE", "TUR", "TZA", "URY", "US1", "VNM"
            ]

In [57]:
for c in countries:
    update_indicator_df(c)

In [52]:
alb_monthly_df = pd.read_csv(r"..\..\data\ouput\country_analysis\v5_indicators\ALB\ALB_all_monthly_metrics_update.csv")

In [53]:
alb_indicators_df =pd.read_csv(r"..\..\data\ouput\country_analysis\v5_indicators\ALB\ALB_prepped_indicators_stat_update.csv")

In [59]:
alb_monthly_df[["changeset_comments_nonai"]]

    changeset_comments_nonai
0                   0.232587
1                   1.862642
2                   0.118172
3                   0.008256
4                   0.161773
5                  10.106802
6                   0.002749
7                   2.210939
8                   0.000000
9                   6.187205
10                  0.077620
11                  0.192586
12                  0.228617
13                  0.130151
14                  0.051364
15                  6.707366
16                  0.668834
17                  0.000000
18                  6.262664
19                  0.000000
20                  0.173873
21                  0.241182
22                 21.264855
23                  0.038749
24                  0.120676
25                  8.312167
26                  0.000000
27                  0.000000
28                  1.849613
29                  0.426936
30                  0.553916
31                  0.023614
32                  0.000000
33                  0.092678
34                  0.051240
35                  0.090597
36                  1.577982
37                  2.462882
38                  0.011976
39                  8.633795
40                 24.432725
41                  0.473566
42                  0.000000
43                  0.009168
44                  0.013727
45                  0.000000
46                  0.000000
47                  0.211150
48                  0.041753
49                  0.000000
50                  0.073726
51                  0.000000
52                  0.336451
53                 15.269119
54                 20.940237
55                  0.030726
56                  0.008410
57                  0.000000
58                  0.015086
59                  0.314835
60                  0.729374
61                  0.304644
62                  0.157916
63                  3.362633
64                  1.345083
65                  0.040936
66                  0.009981
67                  0.071709
68                  6.435382
69                  0.532572
70                  7.831711
71                  0.000000

In [55]:
alb_monthly_df[["months", "contributors_prolific_share_ai","contributors_prolific_ai", "contributors_casual_ai", "contributors_inactive_ai", "contributors_AI"]]

     months  contributors_prolific_share_ai  contributors_prolific_ai  contributors_casual_ai  contributors_inactive_ai  contributors_AI
0   2020-01                        0.000000                       0.0                     0.0                       0.0                2
1   2020-02                        0.000000                       0.0                     0.0                       0.0                2
2   2020-03                        0.000000                       0.0                     0.0                       0.0                0
3   2020-04                        0.000000                       0.0                     1.0                       0.0                2
4   2020-05                        1.000000                       1.0                     0.0                       0.0                1
5   2020-06                        0.000000                       0.0                     0.0                       0.0                0
6   2020-07                        0.000000                       0.0                     0.0                       0.0                0
7   2020-08                        1.000000                       1.0                     0.0                       0.0                0
8   2020-09                        0.500000                       1.0                     1.0                       0.0                2
9   2020-10                        0.500000                       1.0                     1.0                       0.0                1
10  2020-11                        1.000000                       1.0                     0.0                       0.0                1
11  2020-12                        1.000000                       2.0                     0.0                       0.0                0
12  2021-01                        1.000000                       1.0                     0.0                       0.0                1
13  2021-02                        0.500000                       1.0                     1.0                       0.0                2
14  2021-03                        1.000000                       1.0                     0.0                       0.0                1
15  2021-04                        0.000000                       0.0                     0.0                       0.0                0
16  2021-05                        0.000000                       0.0                     0.0                       0.0                0
17  2021-06                        0.000000                       0.0                     0.0                       0.0                0
18  2021-07                        0.000000                       0.0                     0.0                       0.0                0
19  2021-08                        1.000000                       1.0                     0.0                       0.0                1
20  2021-09                        0.000000                       0.0                     0.0                       0.0                0
21  2021-10                        0.000000                       0.0                     0.0                       0.0                0
22  2021-11                        0.000000                       0.0                     0.0                       0.0                0
23  2021-12                        0.000000                       0.0                     0.0                       0.0                0
24  2022-01                        0.000000                       0.0                     0.0                       0.0                0
25  2022-02                        0.000000                       0.0                     0.0                       0.0                0
26  2022-03                        0.000000                       0.0                     0.0                       0.0                0
27  2022-04                        0.000000                       0.0                     0.0                       0.0                0
28  2022-05                        1.000000                       1.0                     0.0                       0.0                1
29  2022-06                        0.000000                       0.0                     0.0                       0.0                0
30  2022-07                        0.000000                       0.0                     0.0                       0.0                0
31  2022-08                        1.000000                       2.0                     0.0                       0.0                4
32  2022-09                        1.000000                       2.0                     0.0                       0.0                2
33  2022-10                        1.000000                       1.0                     0.0                       0.0                2
34  2022-11                        1.000000                       1.0                     0.0                       0.0                1
35  2022-12                        1.000000                       2.0                     0.0                       0.0                2
36  2023-01                        0.666667                       2.0                     1.0                       0.0                2
37  2023-02                        1.000000                       3.0                     0.0                       0.0                5
38  2023-03                        1.000000                       3.0                     0.0                       0.0                4
39  2023-04                        1.000000                       4.0                     0.0                       0.0                5
40  2023-05                        1.000000                       2.0                     0.0                       0.0                4
41  2023-06                        0.333333                       1.0                     1.0                       1.0                6
42  2023-07                        0.666667                       2.0                     1.0                       0.0                5
43  2023-08                        0.500000                       1.0                     1.0                       0.0                9
44  2023-09                        0.400000                       2.0                     1.0                       2.0                8
45  2023-10                        0.250000                       1.0                     3.0                       0.0               10
46  2023-11                        0.250000                       1.0                     1.0                       2.0                9
47  2023-12                        1.000000                       4.0                     0.0                       0.0                2
48  2024-01                        1.000000                       2.0                     0.0                       0.0                7
49  2024-02                        0.666667                       2.0                     0.0                       1.0                7
50  2024-03                        0.000000                       0.0                     0.0                       1.0                8
51  2024-04                        1.000000                       1.0                     0.0                       0.0                3
52  2024-05                        0.000000                       0.0                     0.0                       0.0                5
53  2024-06                        0.500000                       2.0                     1.0                       1.0                4
54  2024-07                        0.333333                       1.0                     2.0                       0.0                8
55  2024-08                        0.600000                       3.0                     1.0                       1.0               13
56  2024-09                        1.000000                       1.0                     0.0                       0.0                7
57  2024-10                        1.000000                       5.0                     0.0                       0.0               11
58  2024-11                        0.666667                       2.0                     0.0                       1.0                8
59  2024-12                        0.000000                       0.0                     3.0                       0.0                7
60  2025-01                        0.500000                       3.0                     2.0                       1.0                8
61  2025-02                        0.200000                       1.0                     3.0                       1.0               11
62  2025-03                        0.000000                       0.0                     2.0                       0.0                5
63  2025-04                        0.400000                       2.0                     2.0                       1.0                8
64  2025-05                        1.000000                       1.0                     0.0                       0.0                7
65  2025-06                        1.000000                       1.0                     0.0                       0.0                9
66  2025-07                        1.000000                       1.0                     0.0                       0.0               11
67  2025-08                        0.750000                       3.0                     1.0                       0.0               11
68  2025-09                        0.500000                       1.0                     1.0                       0.0                4
69  2025-10                        0.250000                       1.0                     3.0                       0.0                5
70  2025-11                        1.000000                       1.0                     0.0                       0.0                7
71  2025-12                        0.500000                       1.0                     1.0                       0.0                5

In [34]:
import numpy as np

In [36]:
print(alb_monthly_df[['contributors_prolific_share_ai_total']].dtypes)
print(alb_indicators_df[['contributors_prolific_share_ai_total']].dtypes)

contributors_prolific_share_ai_total    float64
dtype: object
contributors_prolific_share_ai_total    float64
dtype: object

In [35]:
print(np.isinf(alb_monthly_df['contributors_prolific_share_ai_total']).sum())
print(np.isinf(alb_indicators_df['contributors_prolific_share_ai_total']).sum())

0
0